#!/bin/sh
set -e -u

testdir=$(readlink -f testsuite/)
version=$(ocrad --version | sed -n -e '/GNU [oO]crad \(.*\)/ { s//\1/p }')
ln -sf "$(which ocrad)" "$ADTTMP/"
g++ -g -O2 -Wall -DPROGVERSION="\"$version\"" ocradcheck.cc -locrad -o "$ADTTMP/ocradcheck"
cd "$ADTTMP"
"$testdir/check.sh" "$testdir" "$version"

# vim:ts=4 sw=4 et
